# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("DataAnalysis")
        MainWindow.resize(815, 895)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tips = QtWidgets.QTextBrowser(self.centralWidget)
        self.tips.setObjectName("tips")
        self.gridLayout_2.addWidget(self.tips, 4, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.columnChoice = QtWidgets.QComboBox(self.centralWidget)
        self.columnChoice.setObjectName("columnChoice")
        self.horizontalLayout.addWidget(self.columnChoice)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.symbolChoice = QtWidgets.QComboBox(self.centralWidget)
        self.symbolChoice.setObjectName("symbolChoice")
        self.horizontalLayout.addWidget(self.symbolChoice)
        self.leftLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.leftLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leftLineEdit.setText("")
        self.leftLineEdit.setObjectName("leftLineEdit")
        self.horizontalLayout.addWidget(self.leftLineEdit)
        self.rightLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.rightLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.rightLineEdit.setText("")
        self.rightLineEdit.setObjectName("rightLineEdit")
        self.horizontalLayout.addWidget(self.rightLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableView(self.groupBox_4)
        self.tableWidget.setObjectName("tableWidget")
        self.gridLayout_4.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 4, 1)
        self.dispalyDesc = QtWidgets.QLabel(self.centralWidget)
        self.dispalyDesc.setText("")
        self.dispalyDesc.setObjectName("dispalyDesc")
        self.gridLayout_2.addWidget(self.dispalyDesc, 5, 3, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fileSavePath = QtWidgets.QTextBrowser(self.groupBox_5)
        self.fileSavePath.setMaximumSize(QtCore.QSize(16777215, 40))
        self.fileSavePath.setObjectName("fileSavePath")
        self.gridLayout_5.addWidget(self.fileSavePath, 1, 0, 1, 1)
        self.txtPath = QtWidgets.QTextBrowser(self.groupBox_5)
        self.txtPath.setMaximumSize(QtCore.QSize(16777215, 40))
        self.txtPath.setObjectName("txtPath")
        self.gridLayout_5.addWidget(self.txtPath, 2, 0, 1, 1)
        self.openFilePath = QtWidgets.QTextBrowser(self.groupBox_5)
        self.openFilePath.setMaximumSize(QtCore.QSize(16777215, 40))
        self.openFilePath.setObjectName("openFilePath")
        self.gridLayout_5.addWidget(self.openFilePath, 0, 0, 1, 1)
        self.recoedLog = QtWidgets.QTextBrowser(self.groupBox_5)
        self.recoedLog.setObjectName("recoedLog")
        self.gridLayout_5.addWidget(self.recoedLog, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 2, 1, 1, 3)
        self.gridLayout_2.setColumnStretch(0, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 815, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuTest = QtWidgets.QMenu(self.menuBar)
        self.menuTest.setObjectName("menuTest")
        self.helpBtn = QtWidgets.QMenu(self.menuBar)
        self.helpBtn.setObjectName("helpBtn")
        self.menuStyle = QtWidgets.QMenu(self.menuBar)
        self.menuStyle.setObjectName("menuStyle")
        self.menuMerge = QtWidgets.QMenu(self.menuBar)
        self.menuMerge.setObjectName("menuMerge")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionTest_2 = QtWidgets.QAction(MainWindow)
        self.actionTest_2.setCheckable(True)
        self.actionTest_2.setChecked(True)
        self.actionTest_2.setObjectName("actionTest_2")
        self.actionTest_3 = QtWidgets.QAction(MainWindow)
        self.actionTest_3.setCheckable(True)
        self.actionTest_3.setObjectName("actionTest_3")
        self.actionTest3 = QtWidgets.QAction(MainWindow)
        self.actionTest3.setObjectName("actionTest3")
        self.actionTest3_2 = QtWidgets.QAction(MainWindow)
        self.actionTest3_2.setObjectName("actionTest3_2")
        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setObjectName("actionLight")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionTxt = QtWidgets.QAction(MainWindow)
        self.actionTxt.setObjectName("actionTxt")
        self.actionCheckData = QtWidgets.QAction(MainWindow)
        self.actionCheckData.setObjectName("actionCheckData")
        self.actionScreenData = QtWidgets.QAction(MainWindow)
        self.actionScreenData.setObjectName("actionScreenData")
        self.actionVlookup = QtWidgets.QAction(MainWindow)
        self.actionVlookup.setObjectName("actionVlookup")
        self.actionInitTable = QtWidgets.QAction(MainWindow)
        self.actionInitTable.setObjectName("actionInitTable")
        self.actionMappingTable = QtWidgets.QAction(MainWindow)
        self.actionMappingTable.setObjectName("actionMappingTable")
        self.actionMerge = QtWidgets.QAction(MainWindow)
        self.actionMerge.setObjectName("actionMerge")
        self.actionCheck = QtWidgets.QAction(MainWindow)
        self.actionCheck.setObjectName("actionCheck")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionMergePath = QtWidgets.QAction(MainWindow)
        self.actionMergePath.setObjectName("actionMergePath")
        self.actionMergeFile = QtWidgets.QAction(MainWindow)
        self.actionMergeFile.setObjectName("actionMergeFile")
        self.actionMergeSavePath = QtWidgets.QAction(MainWindow)
        self.actionMergeSavePath.setObjectName("actionMergeSavePath")
        self.menuTest.addAction(self.actionFile)
        self.menuTest.addAction(self.actionCheckData)
        self.menuTest.addAction(self.actionSave)
        self.menuTest.addAction(self.actionTxt)
        self.menuTest.addAction(self.actionScreenData)
        self.helpBtn.addAction(self.actionInitTable)
        self.helpBtn.addAction(self.actionMappingTable)
        self.helpBtn.addAction(self.actionCheck)
        self.helpBtn.addAction(self.actionMerge)
        self.menuStyle.addAction(self.actionLight)
        self.menuStyle.addAction(self.actionDark)
        self.menuMerge.addAction(self.actionMergePath)
        self.menuMerge.addAction(self.actionMergeSavePath)
        self.menuMerge.addAction(self.actionMergeFile)
        self.menuBar.addAction(self.menuTest.menuAction())
        self.menuBar.addAction(self.helpBtn.menuAction())
        self.menuBar.addAction(self.menuMerge.menuAction())
        self.menuBar.addAction(self.menuStyle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tips.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Tips -&gt;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 筛分数据</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. 两张表格vlookup</p></body></html>"))
        self.label.setText(_translate("MainWindow", "ScreenColumn"))
        self.label_2.setText(_translate("MainWindow", "nil"))
        self.menuTest.setTitle(_translate("MainWindow", "File"))
        self.helpBtn.setTitle(_translate("MainWindow", "Vlookup"))
        self.menuStyle.setTitle(_translate("MainWindow", "Style"))
        self.menuMerge.setTitle(_translate("MainWindow", "Merge"))
        self.actionFile.setText(_translate("MainWindow", "Open"))
        self.actionTest_2.setText(_translate("MainWindow", "Test"))
        self.actionTest_3.setText(_translate("MainWindow", "Test"))
        self.actionTest3.setText(_translate("MainWindow", "Test3"))
        self.actionTest3_2.setText(_translate("MainWindow", "Test3"))
        self.actionLight.setText(_translate("MainWindow", "Light"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionSave.setText(_translate("MainWindow", "Path"))
        self.actionTxt.setText(_translate("MainWindow", "Txt"))
        self.actionCheckData.setText(_translate("MainWindow", "View"))
        self.actionScreenData.setText(_translate("MainWindow", "ScreenData"))
        self.actionVlookup.setText(_translate("MainWindow", "Vlookup"))
        self.actionInitTable.setText(_translate("MainWindow", "InitTable"))
        self.actionMappingTable.setText(_translate("MainWindow", "MappingTable"))
        self.actionMerge.setText(_translate("MainWindow", "vlookup"))
        self.actionCheck.setText(_translate("MainWindow", "Check"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionMergePath.setText(_translate("MainWindow", "MergePath"))
        self.actionMergeFile.setText(_translate("MainWindow", "Merge"))
        self.actionMergeSavePath.setText(_translate("MainWindow", "SavePath"))

